<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>TraSt_CSV</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Triamec.Tam.Core" Version="19.0.2-TraSt20250523" />
    <PackageReference Include="Triamec.Tam.TriaLink" Version="7.23.2-TraSt20250523" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TrajectoryStream_Test1.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
